ALTER TABLE "User" ADD COLUMN "authVersion" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "RefreshToken" ADD COLUMN "authVersion" INTEGER NOT NULL DEFAULT 0, ADD COLUMN "sessionId" UUID;
CREATE TABLE "AuthSession" (id UUID PRIMARY KEY, "userId" UUID NOT NULL, "lastActivityAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "AuthSession_userId_idx" ON "AuthSession" ("userId");
